name: Deploy (Development)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          name: "Validate develop"
          environment: development

  open-pr-main:
    needs: [build]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install requests

      - name: Create PR
        run: python .github/scripts/create_pr.py main
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
