name: Deploy (Production)

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          name: "Release version"
          environment: production

      - name: Python Semantic Release
        id: semantic_release
        uses: python-semantic-release/python-semantic-release@v8.3.0
        with:
          github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Get release version
        id: get_version
        if: success() && steps.semantic_release.outputs.released == 'true'
        run: echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Upload release assets
        if: success() && steps.semantic_release.outputs.released == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: |
            ./dist/hbox-${{ steps.get_version.outputs.version }}.tar.gz
            ./dist/hbox-${{ steps.get_version.outputs.version }}-py3-none-any.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-to-test-pypi:
    needs: build-and-release
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          name: "Publish to test.pypi.org"
          environment: production

      - name: Publish to Test PyPI
        if: ${{ needs.build-and-release.outputs.semantic_release.outputs.released == 'true' }}
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
          poetry publish -r test-pypi $PYPI_TOKEN

  publish-to-pypi:
    needs: build-and-release
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          name: "Publish to pypi.org"
          environment: production

      - name: Publish to PyPI
        if: ${{ needs.build-and-release.outputs.semantic_release.outputs.released == 'true' }}
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish

  merge-back-to-develop:
    needs: [publish-to-test-pypi, publish-to-pypi]
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge back to develop
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          git checkout develop
          git merge main
          git push
